export const projects = [
  {
    title: "BotByte AI",
    tagline: "An open source platform for building chatbot with the Assist",
    featuredOn: "2024-06-24T04:37:37.859Z",
    commentCount: 43,
    bookmarkCount: 19,
    id: "PRJH7BJBGMRAGRQ6BH9NADGGK9NL6Q",
    createdBy: {
      firstName: "Sanket",
      lastName: "Bagad",
      displayName: "Sanket Bagad",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocJUw4hNe2hpfr4QO0y5V1OKMd7AiB_TKC96XPoecFdDSzACAehB=s96-c",
      headline:
        "Work Palette: I've dabbled in the realms of MERN, AWS, and Azure—taming the cloud while juggling Docker and Kubernetes.",
      profileHandle: "sanketbagad",
      verified: true,
      id: "UHDNE8GDM9RDB6K3NLD9DG9MORPQ",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNE8GDM9RDB6K3NLD9DG9MORPQ/projects/botbyte-aieb534149-c8e3-4e06-b9fe-c986e8c6c82a.webp?v1.1",
    ],
    collaborators: [
      {
        displayName: "Snehal Bargaje",
        firstName: "Snehal",
        headline:
          "Javascript | Angular | MCA | Seeking Entry-Level Developer Position | Ready to Contribute to Innovative Projects",
        lastName: "Bargaje",
        profileHandle: "snehalbargaje",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UH6AJADR68BPMPMIR7BPMM8DQQR9/h6ajadr68bpmpmir7bpmm8dqqr9-profile.webp",
        verified: true,
        id: "UH6AJADR68BPMPMIR7BPMM8DQQR9",
      },
      {
        firstName: "Ritesh",
        lastName: "Patel",
        displayName: "Ritesh Patel",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHLKN6D96NB9JAE19B67MPL98OLN/hlkn6d96nb9jae19b67mpl98oln-profile.webp",
        headline:
          "Next JS || React JS || Redux || Node JS || Express JS || MongoDB",
        profileHandle: "riteshhh",
        verified: true,
        id: "UHLKN6D96NB9JAE19B67MPL98OLN",
      },
    ],
    projectURL: "/sanketbagad/project/botbyte-ai",
    isUpvoted: false,
    upvotesCount: 41,
  },
  {
    title: "AdLamp",
    tagline: "Auto Optimize AI-Driven PPC Tasks, Save Hours Weekly",
    featuredOn: "2024-06-24T07:56:03.935Z",
    commentCount: 24,
    bookmarkCount: 2,
    id: "PRJHR86KBR68DL8BLHRBJDEEB6QKAQ",
    createdBy: {
      displayName: "Richard Rubenstein",
      firstName: "Richard",
      headline:
        "Marketing-as-a-Service ↬ Data-backed, Digital Campaigns for eCommerce Brands & Startups",
      lastName: "Rubenstein",
      profileHandle: "ricruben",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHLKNN7ANNJDPRGCLANEE9NPNLMR/hlknn7annjdprgclanee9npnlmr-profile.webp",
      verified: true,
      companyVerifiedAt: "2024-05-16T08:23:49.754Z",
      id: "UHLKNN7ANNJDPRGCLANEE9NPNLMR",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHLKNN7ANNJDPRGCLANEE9NPNLMR/projects/adlamp9616bc38-3732-4010-b354-e71b22aac2d4.webp?v1.1",
    ],
    collaborators: [
      {
        displayName: "Emad Ibrahim",
        firstName: "Emad",
        headline:
          "Founder & CTO @EliteCoders | Delivering Innovative Solutions",
        lastName: "Ibrahim",
        profileHandle: "emadibrahm",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHNN6N6PDODNN8O2NNMN68NR7DDK/hnn6n6pdodnn8o2nnmn68nr7ddk-profile",
        verified: true,
        id: "UHNN6N6PDODNN8O2NNMN68NR7DDK",
      },
      {
        displayName: "Keith Mc Manus",
        firstName: "Keith",
        headline: "Digital Marketing",
        lastName: "Mc Manus",
        profileHandle: "keith",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHMQLRKNK887OLJCQ6ODAA99BAGJ/hmqlrknk887oljcq6odaa99bagj-profile.webp",
        companyVerifiedAt: "2024-05-16T08:23:43.221Z",
        verified: true,
        id: "UHMQLRKNK887OLJCQ6ODAA99BAGJ",
      },
    ],
    projectURL: "/ricruben/project/adlamp",
    isUpvoted: false,
    upvotesCount: 41,
  },
  {
    title: "HBD Cake",
    tagline: "Create a magical cake celebration",
    featuredOn: "2024-06-24T04:51:59.972Z",
    commentCount: 6,
    bookmarkCount: 1,
    id: "PRJH6AJNLNDLNNMAB2R7BPMM88DBDE",
    createdBy: {
      firstName: "Neerajkumar",
      displayName: "Neerajkumar Chaudhary",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocKX-NRYZSO8Zy3SzWgPKR7-zrQ_St_290xitMwE8PQ1DkSRN5vP=s96-c",
      headline: "Web Developer | Cybersecurity Enthusiast",
      lastName: "Chaudhary",
      profileHandle: "neerajkumarc",
      id: "UHJKRKG6DP9N8E93APDBMAQNQEJL",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHJKRKG6DP9N8E93APDBMAQNQEJL/projects/hbd-cake3ad648ea-c378-4c68-be2f-df6cf61fc82a.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/neerajkumarc/project/hbd-cake",
    isUpvoted: false,
    upvotesCount: 29,
  },
  {
    title: "Automated Zomato Notifications!",
    tagline: "A friendly automated notification generator",
    featuredOn: "2024-06-24T15:03:39.846Z",
    commentCount: 18,
    bookmarkCount: 3,
    id: "PRJHP696D66NNPAOP1R9JJ86NMR77K",
    createdBy: {
      firstName: "Tejas",
      lastName: "Mankeshwar",
      displayName: "Tejas Mankeshwar",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNENJE8MP6G6N3AGKK9NJMM66M/hdnenje8mp6g6n3agkk9njmm66m-profile",
      headline: "AI & ML Enthusiast | Team Player | Creative Thinker",
      profileHandle: "tejasmankeshwar",
      verified: true,
      id: "UHDNENJE8MP6G6N3AGKK9NJMM66M",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNENJE8MP6G6N3AGKK9NJMM66M/projects/automated-zomato-notifications27473db8-a40f-4c3a-92e1-f5f536e0dc9f.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/tejasmankeshwar/project/automated-zomato-notifications",
    isUpvoted: false,
    upvotesCount: 27,
  },
  {
    title: "Smart Calendar",
    tagline: "AI-powered productivity app for managing schedules and tasks",
    featuredOn: "2024-06-24T08:06:41.086Z",
    commentCount: 20,
    bookmarkCount: 4,
    id: "PRJH8O9ORM68KQGNLCRNP9KADPMPMA",
    createdBy: {
      firstName: "Prashant Kumar",
      lastName: "Singh",
      displayName: "Prashant Kumar Singh",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHR8AQB8MOQP96LFEM8NRQQG9Q9E/hr8aqb8moqp96lfem8nrqqg9q9e-profile.webp",
      headline:
        "Software Developer | Product Designer | Freelancer | IIIT Sonepat",
      profileHandle: "prashantkumar",
      verified: true,
      id: "UHR8AQB8MOQP96LFEM8NRQQG9Q9E",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHR8AQB8MOQP96LFEM8NRQQG9Q9E/projects/lunaticscdfb15cd-7a86-4fa2-b422-d0f57f21b5bb.webp",
    ],
    collaborators: [
      {
        firstName: "Anurag",
        lastName: "Daksh",
        displayName: "Anurag Daksh",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHGNLLBRJKJEQOEHAGD6JQDNO8MJ/hgnllbrjkjeqoehagd6jqdno8mj-profile.webp",
        headline: "Backend Lead @GDSC IIIT Sonepat",
        profileHandle: "anuragdaksh7",
        id: "UHGNLLBRJKJEQOEHAGD6JQDNO8MJ",
      },
    ],
    projectURL: "/prashantkumar/project/smart-calendar",
    isUpvoted: false,
    upvotesCount: 27,
  },
  {
    title: "Tiny Scan",
    tagline: "Effortlessly Dive into URL Details",
    featuredOn: "2024-06-24T04:45:57.351Z",
    commentCount: 3,
    id: "PRJHMQLQKKEMMGQBR2QOLJO7ANOJNO",
    createdBy: {
      firstName: "Anthony",
      displayName: "Anthony H",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHNN6NQE7PJL9J7FPR6RMRQMDEDG/hnn6nqe7pjl9j7fpr6rmrqmdedg-profile.webp",
      headline: "Dev as Life",
      lastName: "H",
      profileHandle: "anthony",
      id: "UHNN6NQE7PJL9J7FPR6RMRQMDEDG",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHNN6NQE7PJL9J7FPR6RMRQMDEDG/projects/tiny-scan8a40b29d-4de5-4044-ba5b-0a78f94da867.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/anthony/project/tiny-scan",
    isUpvoted: false,
    upvotesCount: 17,
  },
  {
    title: "Send To Notion",
    tagline: "Save LinkedIn Profiles to Notion Database in one click",
    featuredOn: "2024-06-24T09:28:49.772Z",
    commentCount: 2,
    id: "PRJH7BJM9K69PANOKINMP966MAJRLM",
    createdBy: {
      firstName: "Varun",
      lastName: "Jaggi",
      displayName: "Varun Jaggi",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNENMA7OGDEJQCNLKRLNQGO6JL/hdnenma7ogdejqcnlkrlnqgo6jl-profile",
      headline: "Backend Developer | Django | Python | FastApi | SaaS",
      profileHandle: "varunjaggi",
      verified: true,
      id: "UHDNENMA7OGDEJQCNLKRLNQGO6JL",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNENMA7OGDEJQCNLKRLNQGO6JL/projects/send-to-notion483b7357-8cc6-4f2a-a59f-19526301a329.webp?v1.1",
    ],
    collaborators: [
      {
        firstName: "Kedare",
        lastName: "Shubham",
        displayName: "Kedare Shubham",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHGNLN7DJ9QQBLL1MKBDKQJEDPPQ/hgnln7dj9qqbll1mkbdkqjedppq-profile",
        headline: "Full Stack Developer | SaaS | Next.js | Django | GO",
        profileHandle: "kedareshubham",
        id: "UHGNLN7DJ9QQBLL1MKBDKQJEDPPQ",
      },
    ],
    projectURL: "/varunjaggi/project/send-to-notion",
    isUpvoted: false,
    upvotesCount: 18,
  },
  {
    title: "Bionic Reading Chrome Extension",
    tagline: "chrome extension that helps in bionic reading ",
    featuredOn: "2024-06-24T01:36:52.127Z",
    commentCount: 6,
    bookmarkCount: 1,
    id: "PRJHR868LP6EJM7GM1DRQLPP6LL8LR",
    createdBy: {
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHR8BPE8LMNOMGA3A67RN9NL6BRA/hr8bpe8lmnomga3a67rn9nl6bra-profile.webp",
      firstName: "Saumitra",
      headline: "cs undergrad | freelance developer",
      lastName: "Kapoor",
      profileHandle: "kapoor",
      displayName: "Saumitra Kapoor",
      verified: false,
      companyVerifiedAt: null,
      id: "UHR8BPE8LMNOMGA3A67RN9NL6BRA",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHR8BPE8LMNOMGA3A67RN9NL6BRA/projects/bionic-reading-chrome-extensioncc33318f-dfbf-42a7-8fc0-1de96e8e60f8.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/kapoor/project/bionic-reading-chrome-extension",
    isUpvoted: false,
    upvotesCount: 15,
  },
  {
    title: "Hire my Peer",
    tagline: "Designing a referral-reward feature for PeerHub",
    featuredOn: "2024-06-24T12:26:01.580Z",
    commentCount: 2,
    id: "PRJH7BJM97LOAPQN6FNMP966M7LB6K",
    createdBy: {
      firstName: "Prathamesh",
      headline:
        "Hi! I'm a product designer & former frontend dev. Into F1, chill chess and good food.\nLearn 🧐 | Create 🏗 | Evolve 🌱",
      lastName: "Sujgure",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHA9BL9PQ7BNRKRIRNAJNNEOMLMM/ha9bl9pq7bnrkrirnajnneomlmm-profile.webp",
      profileHandle: "pdsujgure",
      displayName: "Prathamesh Sujgure",
      verified: false,
      id: "UHA9BL9PQ7BNRKRIRNAJNNEOMLMM",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHA9BL9PQ7BNRKRIRNAJNNEOMLMM/projects/hire-my-peerbd047614-9472-4f99-988a-dfac61125fe5.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/pdsujgure/project/hire-my-peer",
    isUpvoted: false,
    upvotesCount: 16,
  },
  {
    title: "QuizRise",
    tagline: "Quiz Generator Make Learning Easy",
    featuredOn: "2024-06-24T05:53:23.521Z",
    id: "PRJHGNLNDP9LL6P7AHKDP977R8DK78",
    createdBy: {
      displayName: "İbrahim Oğuzhan ULUKAYA",
      firstName: "İbrahim Oğuzhan",
      headline:
        "Frontend Developer - POPUPSMART\n\n- 🔭 I'm currently working at Popupsmart.\n- 🌱 I'm building the QuizRise Quiz maker 💻",
      lastName: "ULUKAYA",
      profileHandle: "oguz3",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHP696EGBP7A6QNH6KA9EEBQKPKQ/hp696egbp7a6qnh6ka9eebqkpkq-profile.webp",
      verified: true,
      id: "UHP696EGBP7A6QNH6KA9EEBQKPKQ",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHP696EGBP7A6QNH6KA9EEBQKPKQ/projects/quizrise4d4f3e16-fc75-4f9a-a713-92cb76926edb.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/oguz3/project/quizrise",
    isUpvoted: false,
    upvotesCount: 13,
  },
  {
    title: "Quick CMS",
    tagline: "Headless CMS for Landing Pages",
    featuredOn: "2024-06-24T04:49:52.693Z",
    commentCount: 1,
    id: "PRJH6AJNL779M6JB9HR7BPMM8EEKON",
    createdBy: {
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHR8BLJBPJ9AOQRFMJROLLDE88E9/c65d3313-ad1d-454a-97c7-4c2816145257.jpg",
      firstName: "Siemen",
      headline: "Frontend Web developer with design skills",
      lastName: "Subbaiah",
      profileHandle: "siemen_subbaiah",
      displayName: "Siemen Subbaiah",
      verified: true,
      id: "UHR8BLJBPJ9AOQRFMJROLLDE88E9",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHR8BLJBPJ9AOQRFMJROLLDE88E9/projects/quick-cms6287a358-ed04-40ec-86e7-a525b0ca9ec3.webp?v1.1",
    ],
    collaborators: [
      {
        firstName: "Raghul",
        lastName: "M",
        displayName: "Raghul M",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHEOLOMN8BKAA8ECBAQE87MOP9OP/heolomn8bkaa8ecbaqe87mop9op-profile",
        headline: "UX designer",
        profileHandle: "raghul",
        id: "UHEOLOMN8BKAA8ECBAQE87MOP9OP",
      },
    ],
    projectURL: "/siemen_subbaiah/project/quick-cms",
    isUpvoted: false,
    upvotesCount: 12,
  },
  {
    title: "Coolshapes Vue",
    tagline: "A Vue component library for coolshapes with little grainy gr",
    featuredOn: "2024-06-24T03:02:15.706Z",
    commentCount: 3,
    id: "PRJHOK7KRKBAQNM8JC7Q99E8MGM9EJ",
    createdBy: {
      firstName: "Robert",
      lastName: "Shaw",
      displayName: "Robert Shaw",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UH8OJEPBQGRRK7G298B9JDE8EBK9/h8ojepbqgrrk7g298b9jde8ebk9-profile.webp",
      headline:
        "🖖 Indie maker, build products & share journey in public\n\n🗂️ sidespace.app\n🏷️ onetab.group\n🔖 bookmark.style",
      verified: true,
      profileHandle: "robert_shaw",
      id: "UH8OJEPBQGRRK7G298B9JDE8EBK9",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UH8OJEPBQGRRK7G298B9JDE8EBK9/projects/coolshapes-vuefce7d882-5038-47fd-a96a-0daf9503d479.webp?v1.1",
    ],
    collaborators: [
      {
        firstName: "vijay",
        lastName: "verma",
        displayName: "vijay verma",
        profilePicture:
          "https://lh3.googleusercontent.com/a-/AOh14GiigRktnPHZnugnl5ziESXL9YydqIaFt888keuw0n0=s96-c",
        headline:
          "A Wizard ✦ Love design + Code ✦ building 3dicons and 6+✦ Making tools & designs @OverlayzStudio ✦ Now making own game",
        profileHandle: "realvjy",
        verified: true,
        id: "UHEO6G9EM8AMREK3BD8L7AMPP9NM",
      },
    ],
    projectURL: "/robert_shaw/project/coolshapes-vue",
    isUpvoted: false,
    upvotesCount: 11,
  },
  {
    title: "InterviewGenie",
    tagline: "Practice job interview questions form your job description.",
    featuredOn: "2024-06-24T05:06:59.532Z",
    commentCount: 3,
    bookmarkCount: 1,
    id: "PRJHP696EPKJ9GDRRF6KA9EEBQNOOE",
    createdBy: {
      firstName: "Avinash",
      lastName: "Gupta",
      displayName: "Avinash Gupta",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHOKQER7BOE8KD63GOPLLDKLA6K8/hokqer7boe8kd63goplldkla6k8-profile.webp",
      headline:
        "Frontend Developer | Expert in React, TypeScript & Next.js | Passionate about creating Responsive & High-Performance app",
      profileHandle: "tier3guy",
      verified: true,
      id: "UHOKQER7BOE8KD63GOPLLDKLA6K8",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHOKQER7BOE8KD63GOPLLDKLA6K8/projects/interviewgeniedd677b85-715e-4df5-bc44-b4115a415df9.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/tier3guy/project/interviewgenie",
    isUpvoted: false,
    upvotesCount: 9,
  },
  {
    title: "Inrō",
    tagline: "AI Powered Instagram Marketing Automation",
    featuredOn: "2024-06-24T12:42:57.649Z",
    commentCount: 2,
    bookmarkCount: 2,
    id: "PRJHGNLR8ED66MQ69HDEJK88E6MQPD",
    createdBy: {
      firstName: "Kshitij",
      lastName: "Maheshwari",
      displayName: "Kshitij Maheshwari",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHJKRKBDL6LALJB1O7PKJKQJAAEO/hjkrkbdl6laljb1o7pkjkqjaaeo-profile.webp",
      headline: "Building Inrō",
      profileHandle: "kshitij11",
      verified: true,
      id: "UHJKRKBDL6LALJB1O7PKJKQJAAEO",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHJKRKBDL6LALJB1O7PKJKQJAAEO/projects/inr99c212d4-3565-4dac-a2cb-5652376b3f50.webp?v1.1",
    ],
    collaborators: [
      {
        firstName: "Etienne",
        lastName: "Gatti",
        displayName: "Etienne Gatti",
        headline:
          "CEO @Inrō - AI-Powered Marketing Automation for Social Media",
        profileHandle: "etienneinro",
        profilePicture:
          "https://dqy38fnwh4fqs.cloudfront.net/UHBABA7LMB8J7M7CPDANKNQP8DRM/hbaba7lmb8j7m7cpdanknqp8drm-profile",
        verified: true,
        id: "UHBABA7LMB8J7M7CPDANKNQP8DRM",
      },
    ],
    projectURL: "/kshitij11/project/inr",
    isUpvoted: false,
    upvotesCount: 9,
  },
  {
    title: "Classic Snake Game",
    tagline: "A snake game built using Javascript",
    featuredOn: "2024-06-24T17:57:17.832Z",
    commentCount: 4,
    id: "PRJHJKRK9EMNQP6ALCKGOD9P8DOPP9",
    createdBy: {
      firstName: "Bibek",
      lastName: "Kakati",
      displayName: "Bibek Kakati",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocLsTTNv3cciTfx2NcrmVUd9cAOEHv6s7sSZiKiPxgWXtsQ=s96-c",
      headline: "Software Engineer 👨🏻‍💻| Innovating Tomorrow's Techscape 🚀",
      profileHandle: "bibekkakati",
      id: "UH8O99JL78MBNQK1P6GEOMEOQJ7B",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UH8O99JL78MBNQK1P6GEOMEOQJ7B/projects/classic-snake-game24344b27-fdf5-4b02-9c0f-725c18136729.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/bibekkakati/project/classic-snake-game",
    isUpvoted: false,
    upvotesCount: 8,
  },
  {
    title: "Co-Learn App UX Case-Study",
    tagline: "From Isolation to Interaction: Co-Learn App UX Case Study",
    featuredOn: "2024-06-24T06:34:28.309Z",
    bookmarkCount: 1,
    id: "PRJHEOLOR6GOGL9RL3GDJ7A9APAJEL",
    createdBy: {
      displayName: "Vinay Juneja",
      firstName: "Vinay",
      headline:
        "※ Building @framernewslettr🚀 ※ I Craft High-Converting Landing Pages ✨ ※ Official Verified @Framer Partner ※ @Framer No",
      lastName: "Juneja",
      profileHandle: "uxvinayj",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNGJANAEJ7MARILO7MAAJO88OP/hdngjanaej7marilo7maajo88op-profile.webp",
      verified: false,
      companyVerifiedAt: null,
      id: "UHDNGJANAEJ7MARILO7MAAJO88OP",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNGJANAEJ7MARILO7MAAJO88OP/projects/colearn-app-ux-casestudydee515e6-3d0c-4dd6-a116-93dd9bb250df.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/uxvinayj/project/colearn-app-ux-casestudy",
    isUpvoted: false,
    upvotesCount: 12,
  },
  {
    title: "PrepPro",
    tagline: "Ace Your Interviews with Confidence.",
    featuredOn: "2024-06-24T11:00:08.606Z",
    commentCount: 4,
    id: "PRJHA9N6B7AP6ENK6CRD7ANND8E6QK",
    createdBy: {
      firstName: "Jay",
      lastName: "Patel",
      displayName: "Jay Patel",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocLyj4lqIY-2HzmGec1JnrvCmdGiy9--xDyEPIq8ZlIuwABM5Q=s96-c",
      headline: "Computer Science Student @UNSW",
      profileHandle: "jaypatel7677",
      id: "UHMQLNAGOGRMNKMC6J79NNMNALO6",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHMQLNAGOGRMNKMC6J79NNMNALO6/projects/preppro24a14ef7-12f6-46ba-b443-b28e18e74c11.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/jaypatel7677/project/preppro",
    isUpvoted: false,
    upvotesCount: 6,
  },
  {
    title: "Design Portfolio | 2024-2025",
    tagline: "My designs in UI/UX and more at one place for 2024-25",
    featuredOn: "2024-06-24T04:40:45.277Z",
    commentCount: 4,
    id: "PRJHMQLQ9K67J8L6G36OBJPAE7LBA9",
    createdBy: {
      firstName: "Trishabh",
      lastName: "Vats",
      displayName: "Trishabh Vats",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHNN6MRJMARQMGGFNMDEDQ7D67NQ/hnn6mrjmarqmggfnmdedq7d67nq-profile.webp",
      headline: "UI Designer at Lollypop Design Studio",
      profileHandle: "ayetrissab",
      verified: true,
      id: "UHNN6MRJMARQMGGFNMDEDQ7D67NQ",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHNN6MRJMARQMGGFNMDEDQ7D67NQ/projects/design-portfolio--20242025b6e5ba0c-df37-48a1-817a-b7dfde8d0ce8.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/ayetrissab/project/design-portfolio--20242025",
    isUpvoted: false,
    upvotesCount: 6,
  },
  {
    title: "Devvault",
    tagline: "Platform for sharing and discovering reusable code snippets.",
    featuredOn: "2024-06-24T02:47:02.985Z",
    bookmarkCount: 0,
    id: "PRJHLKNRER9GQKQNBIL7KMBBOO8J6E",
    createdBy: {
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNED9DQMLRQ9OC7LM76NMNAB7O/hdned9dqmlrq9oc7lm76nmnab7o-profile.webp",
      displayName: "Anuj Chhikara",
      firstName: "Anuj",
      headline:
        "I specialize in full-stack webDev, with a primary focus on utilizing React, Next.js, and Node.js technologies.",
      lastName: "Chhikara",
      profileHandle: "anujchhikara",
      id: "UHDNED9DQMLRQ9OC7LM76NMNAB7O",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNED9DQMLRQ9OC7LM76NMNAB7O/projects/devvault62af29a8-f011-4b68-9976-67ffaafb4e79.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/anujchhikara/project/devvault",
    isUpvoted: false,
    upvotesCount: 9,
  },
  {
    title: "we-chat",
    tagline: "Connect Instantly: Your Chat, Powered by React and Firebase",
    featuredOn: "2024-06-24T07:59:47.296Z",
    commentCount: 3,
    id: "PRJHOK7KO9PQALQGQIPJBPP6E9KO6A",
    createdBy: {
      firstName: "Dev",
      lastName: "Mehta",
      displayName: "Dev Mehta",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNENP8O7O8Q98H7B877P9KQ9KO/hdnenp8o7o8q98h7b877p9kq9ko-profile",
      headline: "Software Developer @MyAnatomy | VIT'23",
      profileHandle: "devmehta",
      id: "UHDNENP8O7O8Q98H7B877P9KQ9KO",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNENP8O7O8Q98H7B877P9KQ9KO/projects/wechat887eddf2-dbeb-4fdc-b31b-a530730a48f6.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/devmehta/project/wechat",
    isUpvoted: false,
    upvotesCount: 5,
  },
  {
    title: "Atomic Design Systems",
    tagline: "Unleash Design Efficiency with My Atomic Design Figma System",
    featuredOn: "2024-06-24T07:19:20.050Z",
    id: "PRJHP69JQ7N8EMM8LCKDP6QQDBN87A",
    createdBy: {
      firstName: "Ayush",
      displayName: "Ayush Bajpai",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocJf2M7iITGRhmDX4aSr4GW7zB9LeOXfjmo7QBjdLWD6hFzpOOsr2g=s96-c",
      headline:
        "Product Designer @ Foundership | Ex-AbInBev | MLSA | Postman Student Expert | Framer",
      lastName: "Bajpai",
      profileHandle: "ayussxh",
      id: "UHKKNJ8A7L7MR8Q3LRPOJJRNAKQP",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHKKNJ8A7L7MR8Q3LRPOJJRNAKQP/projects/atomic-design-systemsa851858a-a8d8-42b8-b914-807edfa37b38.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/ayussxh/project/atomic-design-systems",
    isUpvoted: false,
    upvotesCount: 8,
  },
  {
    title: "TrueAlly",
    tagline: "Beat porn addiction with daily activities and learning",
    featuredOn: "2024-06-24T16:18:21.211Z",
    id: "PRJHOK7GDAKGK66PL1AKJ8PPK977GN",
    createdBy: {
      firstName: "Fabián",
      displayName: "Fabián Monsalve",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHJKRKEBGNPAD9R1AB97JRJ9R7LA/hjkrkebgnpad9r1ab97jrj9r7la-profile.webp",
      headline: "Senior Software Engineer at Cosigned",
      lastName: "Monsalve",
      profileHandle: "buildtheui",
      id: "UHJKRKEBGNPAD9R1AB97JRJ9R7LA",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHJKRKEBGNPAD9R1AB97JRJ9R7LA/projects/trueally8d078aea-e75e-4307-8956-e9b40023999b.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/buildtheui/project/trueally",
    isUpvoted: false,
    upvotesCount: 8,
  },
  {
    title: "Youtube Playlist Randomizer",
    tagline: "Shuffle any youtube playlist online ad free",
    featuredOn: "2024-06-24T00:04:55.557Z",
    commentCount: 1,
    id: "PRJH6AJNLG6O69JN63R7BPMM86M9JM",
    createdBy: {
      firstName: "Austin",
      displayName: "Austin Gray",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UH7BJM9PK6PADPJH9NADGGKBGQBD/h7bjm9pk6padpjh9nadggkbgqbd-profile.webp",
      headline: "I like to make websites :D",
      lastName: "Gray",
      profileHandle: "tumbleweed",
      id: "UH7BJM9PK6PADPJH9NADGGKBGQBD",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UH7BJM9PK6PADPJH9NADGGKBGQBD/projects/youtube-playlist-randomizerbd1e3aff-8f76-4c6f-a38c-d5d37d49a128.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/tumbleweed/project/youtube-playlist-randomizer",
    isUpvoted: false,
    upvotesCount: 6,
  },
  {
    title: "Cricket Maniac Beta",
    tagline: "A game made using react three fibre ",
    featuredOn: "2024-06-24T10:13:59.372Z",
    id: "PRJHNN6JQPQMAKRAOHPADONNAEA86K",
    createdBy: {
      firstName: "Lakshay",
      lastName: "Jain",
      displayName: "Lakshay Jain",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNEN6BORMBOQQHNMEG668QQPQE/hdnen6bormboqqhnmeg668qqpqe-profile.webp",
      headline: "Student at Bharati Vidyapeeth's College of Engineering",
      profileHandle: "lakshay_jain",
      verified: true,
      id: "UHDNEN6BORMBOQQHNMEG668QQPQE",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNEN6BORMBOQQHNMEG668QQPQE/projects/cricket-maniacef02daf9-7f25-4f96-a8d9-3e629fd8e8bd.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/lakshay_jain/project/cricket-maniac-beta",
    isUpvoted: false,
    upvotesCount: 6,
  },
  {
    title: "AI PowerPoint Maker",
    tagline: "AI presentation generator for PowerPoint",
    featuredOn: "2024-06-24T17:09:35.034Z",
    id: "PRJHR868PRLBMKA7A2EO7ROQKMQNK9",
    createdBy: {
      firstName: "Daniel",
      lastName: "Li",
      displayName: "Daniel Li",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocKo5cPnf2yJv-g0goB6bSeiJJJKVyXPQVpTck8p_UkiBHLDNg=s96-c",
      headline: "Working on AI PowerPoint Maker",
      profileHandle: "daniel_li",
      id: "UH6AJA9PKKR6ALK2O6J76BK989MP",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UH6AJA9PKKR6ALK2O6J76BK989MP/projects/ai-powerpoint-maker8b842a55-1fbc-4275-a7b7-21981ef4ab45.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/daniel_li/project/ai-powerpoint-maker",
    isUpvoted: false,
    upvotesCount: 5,
  },
  {
    title: "Tripify - AI Powered Travel Planner",
    tagline: "An AI based travel manager: Explore hidden gems, make your p",
    featuredOn: "2024-06-24T16:59:30.757Z",
    id: "PRJH8O9PAQGEO7AEE19MNRDDM8DJQG",
    createdBy: {
      firstName: "Kailash",
      lastName: "Sharma",
      profilePicture:
        "https://dqy38fnwh4fqs.cloudfront.net/UHDNG7BPPO7D9JBH7GGAKO9E7GEL/hdng7bppo7d9jbh7ggako9e7gel-profile.webp",
      displayName: "Kailash Sharma",
      headline:
        "Modern Android Developer | Kotlin -Ktor Backend Developer | Python | Java | 3P's in my life - Programming | Photoshop |",
      profileHandle: "thekaailash",
      verified: true,
      id: "UHDNG7BPPO7D9JBH7GGAKO9E7GEL",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHDNG7BPPO7D9JBH7GGAKO9E7GEL/projects/tripify--ai-powered-travel-planner5260301e-944f-4bc6-a3c1-6f83c6823775.webp?v1.1",
    ],
    collaborators: [
      {
        firstName: "Nandini",
        lastName: "Singh",
        profilePicture:
          "https://lh3.googleusercontent.com/a/AAcHTtey1sKB_p2nyP9qnOJtMnYP4ZnTQVtgYOujXcXyps2dwaA=s96-c",
        displayName: "Nandini Singh",
        headline: "Content writer | App & Web developer",
        profileHandle: "nandini",
        id: "UHR8AMGEKDJNB6DHRQA86RDLJR8M",
      },
    ],
    projectURL: "/thekaailash/project/tripify--ai-powered-travel-planner",
    isUpvoted: false,
    upvotesCount: 5,
  },
  {
    title: "TwitterClone",
    tagline: "a clone to showcase my skills",
    featuredOn: "2024-06-24T10:31:56.694Z",
    id: "PRJHLKNREPNKOONOO376AL996KMERO",
    createdBy: {
      firstName: "Armaan",
      lastName: "Thakur",
      profilePicture:
        "https://lh3.googleusercontent.com/a/AAcHTte4DnqpZag0mzw8xCmDV3PwGxjXPtDeBkqMeV0VD2rNQA=s96-c",
      displayName: "Armaan Thakur",
      headline: "Fullstack Web Developer",
      profileHandle: "armaan23",
      id: "UHLK98LQLMEKEOM1L6QPQQBPQABN",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHLK98LQLMEKEOM1L6QPQQBPQABN/projects/twitterclonef9b5a368-8bff-4712-b64a-e89ce7d0970e.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/armaan23/project/twitterclone",
    isUpvoted: false,
    upvotesCount: 5,
  },
  {
    title: "Recipe Search By Ingredients",
    tagline: "Search recipes by ingredients. Tons of recipes to choose.",
    featuredOn: "2024-06-24T02:13:01.505Z",
    id: "PRJH7BJM9BA7BMN9939NADGGKKPA99",
    createdBy: {
      firstName: "Steve",
      displayName: "Steve ross",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocLxrPz197hQNfP-eJ2cfM4X9Nloj-Fo73JkoUw2eKxKUVMQMg=s96-c",
      headline: "I make silly websites",
      lastName: "ross",
      profileHandle: "recipescal",
      id: "UHA9N6B9ORDQPQGIAR86OOQQ7OQK",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHA9N6B9ORDQPQGIAR86OOQQ7OQK/projects/recipe-search-by-ingredientseb2c0676-72b3-47fb-a7c4-1dc5fce86bf2.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/recipescal/project/recipe-search-by-ingredients",
    isUpvoted: false,
    upvotesCount: 5,
  },
  {
    title: "BillboardGrid",
    tagline: "Showcase your products/ services .. anything for $1",
    featuredOn: "2024-06-24T11:07:16.257Z",
    id: "PRJHQ797NRPPNMBMQCDEGDDKNQARRP",
    createdBy: {
      firstName: "Tj",
      displayName: "Tj Doe",
      profilePicture:
        "https://lh3.googleusercontent.com/a/ACg8ocL2Puj3sn1KfEG8j_dWRmZI7_cfKSpB59SrADF4kVpN=s96-c",
      headline:
        "Founder of Context Bio - ctx.bio\nI also developed https://BillboardGrid.com in 2 weeks to see if I can. I could.",
      lastName: "Doe",
      profileHandle: "tjmakingof",
      id: "UHMQLMOKGOD69OAFQLR7RMA7LLJ7",
    },
    images: [
      "https://dqy38fnwh4fqs.cloudfront.net/UHMQLMOKGOD69OAFQLR7RMA7LLJ7/projects/billboardgrid20643de0-9514-401e-ad26-ea173c0e9a8b.webp?v1.1",
    ],
    collaborators: [],
    projectURL: "/tjmakingof/project/billboardgrid",
    isUpvoted: false,
    upvotesCount: 4,
  },
];

export const topics = [
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNN9",
    name: "Web Development",
    usersCount: 531,
    scrollCount: 2127,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRR8",
    name: "Product Design",
    usersCount: 445,
    scrollCount: 1277,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86QR",
    name: "Jobs & Referrals",
    usersCount: 470,
    scrollCount: 491,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76QK",
    name: "Hiring",
    usersCount: 393,
    scrollCount: 303,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NROR",
    name: "Open Source",
    usersCount: 382,
    scrollCount: 615,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8GB",
    name: "Marketing",
    usersCount: 129,
    scrollCount: 1015,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDN79",
    name: "Writing",
    usersCount: 118,
    scrollCount: 242,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRM8",
    name: "Artificial Intelligence",
    usersCount: 335,
    scrollCount: 539,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86KR",
    name: "Side Project",
    usersCount: 366,
    scrollCount: 1189,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76DK",
    name: "Productivity",
    usersCount: 297,
    scrollCount: 907,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NRDR",
    name: "Books",
    usersCount: 183,
    scrollCount: 160,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8NB",
    name: "Freelancing",
    usersCount: 359,
    scrollCount: 172,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNQ9",
    name: "Startups",
    usersCount: 448,
    scrollCount: 674,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGR78",
    name: "Technology Trends",
    usersCount: 343,
    scrollCount: 946,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD869R",
    name: "Product Management",
    usersCount: 206,
    scrollCount: 441,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM769K",
    name: "Events",
    usersCount: 108,
    scrollCount: 273,
    relatedTopics: [],
  },
  {
    id: "TOPH6AJ7EOEJQDAD7FGKPNRJA9NRPR",
    name: "Security",
    usersCount: 93,
    scrollCount: 272,
    relatedTopics: [],
  },
  {
    id: "TOPH9OLBP8PLQMOMBCDMBO8LQ6O8BB",
    name: "Software Engineering",
    usersCount: 380,
    scrollCount: 1760,
    relatedTopics: [],
  },
  {
    id: "TOPHDNEDLRLEB6N6DFAPGDNOKLDNG9",
    name: "Indie Hacking",
    usersCount: 186,
    scrollCount: 222,
    relatedTopics: [],
  },
  {
    id: "TOPHJKRN9D9RLMKMNHA8BGRJLKGRB8",
    name: "Build In Public",
    usersCount: 289,
    scrollCount: 607,
    relatedTopics: [],
  },
  {
    id: "TOPHMQL6DJDL87Q76IBA986LGD86NR",
    name: "Startup News",
    usersCount: 264,
    scrollCount: 276,
    relatedTopics: [],
  },
  {
    id: "TOPHP69L7M79BE6EL1RL976GJM76EK",
    name: "Mobile Apps",
    usersCount: 229,
    scrollCount: 488,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ969",
    name: "AMA",
    usersCount: 43,
    scrollCount: 28,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7OMG",
    name: "Work Memes",
    usersCount: 126,
    scrollCount: 43,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8OR9",
    name: "Devops",
    usersCount: 118,
    scrollCount: 128,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLM8K",
    name: "System Design",
    usersCount: 293,
    scrollCount: 100,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89EP",
    name: "Competitive Programming",
    usersCount: 100,
    scrollCount: 50,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAER",
    name: "Finance & Investing",
    usersCount: 102,
    scrollCount: 241,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ989",
    name: "DSA",
    usersCount: 158,
    scrollCount: 48,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7OAG",
    name: "Data Science",
    usersCount: 84,
    scrollCount: 85,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8OL9",
    name: "Career Guidance",
    usersCount: 162,
    scrollCount: 338,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLMJK",
    name: "Hardware",
    usersCount: 56,
    scrollCount: 55,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89BP",
    name: "Web3",
    usersCount: 145,
    scrollCount: 47,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAGR",
    name: "Help Needed",
    usersCount: 76,
    scrollCount: 182,
    relatedTopics: [],
  },
  {
    id: "TOPHEOLGJ7JLD8O8GCGEDQ9ALRQ9N9",
    name: "SAAS",
    usersCount: 234,
    scrollCount: 389,
    relatedTopics: [],
  },
  {
    id: "TOPHKKNDAEAN6OKODHQ6G7OEBD7O9G",
    name: "Developer Tools",
    usersCount: 238,
    scrollCount: 890,
    relatedTopics: [],
  },
  {
    id: "TOPHNN67EKE6R9N97FKBG8OM7J8O99",
    name: "Shitposting",
    usersCount: 78,
    scrollCount: 106,
    relatedTopics: [],
  },
  {
    id: "TOPHQ79M8689DJ7JMHBKALMRQOLMNK",
    name: "Sales",
    usersCount: 49,
    scrollCount: 406,
    relatedTopics: [],
  },
  {
    id: "TOPH7BJ8O6OJQGBG8CJ7D89LOR89KP",
    name: "Opinions",
    usersCount: 83,
    scrollCount: 49,
    relatedTopics: [],
  },
  {
    id: "TOPHA9NEQKQN8L9LECK96BALPJBAQR",
    name: "Ask Peerlist",
    usersCount: 146,
    scrollCount: 26,
    relatedTopics: [],
  },
];
export const roles = [
  "Android Developer",
  "Web Developer",
  "Software Developer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Analyst",
  "Machine Learning Engineer",
  "Project Manager",
  "Product Manager",
  "UI/UX Designer",
  "QA Engineer",
  "Database Administrator",
  "Network Engineer",
  "Security Analyst",
  "Systems Architect",
  "Cloud Engineer",
  "Mobile Developer",
  "Blockchain Developer",
  "Game Developer",
  "IT Support Specialist",
  "Business Analyst",
  "Technical Writer",
];
export const joboptions = ["Full-time", "Part-time", "Contract", "Internship"];
export const integrations = [
  {
    id: 1,
    title: "DEV",
    image:
      "https://media.dev.to/cdn-cgi/image/quality=100/https://dev-to-uploads.s3.amazonaws.com/uploads/logos/resized_logo_UQww2soKuUsjaOGNB38o.png",
  },
  {
    id: 2,
    title: "Github",
    image:
      "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png",
  },
  {
    id: 3,
    title: "Youtube",
    image:
      "https://t3.ftcdn.net/jpg/07/22/13/68/240_F_722136822_VIVcS7fxKb4ippA6kRYCoLwvS0J69hpB.jpg",
  },
];
export const months = [
  { id: 1, name: "Jan" },
  { id: 2, name: "Feb" },
  { id: 3, name: "Mar" },
  { id: 4, name: "Apr" },
  { id: 5, name: "May" },
  { id: 6, name: "Jun" },
  { id: 7, name: "July" },
  { id: 8, name: "Aug" },
  { id: 9, name: "Sept" },
  { id: 10, name: "Oct" },
  { id: 11, name: "Nov" },
  { id: 12, name: "Dec" },
];
export const years = Array.from({ length: 2024 - 2000 + 1 }, (_, i) => ({
  id: 2000 + i,
  name: 2000 + i,
}));
export const degrees = [
  { id: 1, name: "Associate" },
  { id: 2, name: "Bachelor" },
  { id: 3, name: "Master" },
  { id: 4, name: "Doctorate" },
  { id: 5, name: "Professional" },
  { id: 6, name: "Certificate" },
  { id: 7, name: "Diploma" },
  { id: 8, name: "Advanced Diploma" },
  { id: 9, name: "Honours" },
  { id: 10, name: "Fellowship" },
];
